---
image: registry.git.coop/webarch/containers/images/ansible:0.18.0
before_script:
  - chmod 700 $(pwd)
stages:
  - lint
lint:
  stage: lint
  script:
    - yamllint .
    - molecule lint
# vim: syntax=yaml
...
