# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Yarn Ansible role.
#
# The Webarchitects Yarn Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Yarn Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Yarn Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Gather distro facts
      ansible.builtin.setup:
        gather_subset:
          - distribution

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Debian Trixie and newer
      block:

        - name: Stat /etc/apt/keyrings/yarn.gpg
          ansible.builtin.stat:
            path: /etc/apt/keyrings/yarn.gpg
          register: molecule_yarn_gpg

        - name: Stat /etc/apt/sources.list.d/yarn.sources
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/yarn.sources
          register: molecule_yarn_sources

        - name: Check that that the yarn package, sources and GPG public keys are absent
          ansible.builtin.assert:
            that:
              - ("yarn" not in ansible_facts.packages.keys())
              - not molecule_yarn_gpg.stat.exists | bool
              - not molecule_yarn_sources.stat.exists | bool

      when:
        - ansible_facts.distribution == "Debian"
        - ansible_facts.distribution_major_version is ansible.builtin.version('12', '>')

    - name: Debian Bookworm and older
      block:

        - name: Check that yarn package is present
          ansible.builtin.assert:
            that:
              - ("yarn" in ansible_facts.packages.keys())

        - name: Check the latest available version of Yarn
          ansible.builtin.uri:
            url: https://github.com/yarnpkg/yarn/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          register: molecule_yarn_headers

        - name: Set a fact for the latest version of Yarn
          ansible.builtin.set_fact:
            molecule_yarn_latest: "{{ molecule_yarn_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"

        - name: Debug the latest version of Yarn
          ansible.builtin.debug:
            var: molecule_yarn_latest
            verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

        - name: Which Yarn
          ansible.builtin.command: which yarn
          check_mode: false
          changed_when: false
          register: molecule_which_yarn

        - name: Debug which yarn
          ansible.builtin.debug:
            var: molecule_which_yarn.stdout
            verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

        - name: Check installed Yarn version
          ansible.builtin.command: yarn --version
          check_mode: false
          changed_when: false
          register: molecule_yarn_version

        - name: Debug Yarn version stdout
          ansible.builtin.debug:
            var: molecule_yarn_version.stdout
            verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

        - name: Debug the installed version of Yarn
          ansible.builtin.debug:
            var: molecule_yarn_version
            verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

        - name: Check that the installed version of Yarn matches the latest version of Yarn
          ansible.builtin.assert:
            that:
              - molecule_yarn_version.stdout == molecule_yarn_latest
            fail_msg: >-
              The installed version of Yarn is {{ molecule_yarn_version.stdout }} and the latest version is {{ molecule_yarn_latest }}

      when:
        - ansible_facts.distribution == "Debian"
        - ansible_facts.distribution_major_version is ansible.builtin.version('12', '<=')
...
